# Generated by Django 5.1.2 on 2024-10-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billfile', models.FileField(upload_to='bill/')),
                ('uploading_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
