# Generated by Django 5.1.2 on 2024-10-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pdffile_desc_pdffile_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='qty',
        ),
    ]
